steps:
  - name: Checkout code  # Step 1: Fetching code
    uses: actions/checkout@v2

  - name: Set up Node.js  # Step 2: Setting up Node.js environment
    uses: actions/setup-node@v2
    with:
      node-version: '16'  # Using Node.js version 16

  - name: Install dependencies  # Step 3: Installing dependencies
    run: npm install

  - name: Run tests  # Step 4: Running tests
    run: npm test

  - name: Build and deploy  # Step 5: Building and deploying
    run: |
      npm run build
      # Add your deployment commands here
